export const LOGIN_SUCCESS = 'USER.LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'USER.SIGNUP_SUCCESS';
export const SIGNOUT = 'USER.SIGNOUT';
export const SHOW_PROFILE_MODAL = 'USER.SHOW_PROFILE_MODAL';
export const HIDE_PROFILE_MODAL = 'USER.HIDE_PROFILE_MODAL';
export const SHOW_EMAIL_MODAL = 'USER.SHOW_EMAIL_MODAL';
export const HIDE_EMAIL_MODAL = 'USER.HIDE_EMAIL_MODAL';